Add Visualization Feature to console.log (#52)
# Overview

Hello. I have some suggestions to make regarding the use of the service.

## Features

- Modify the existing Log to add color to make it more noticeable
- Add error log

## Expected Effects

- Clarity of error messages, ease of integration with logging systems:
After the change, error messages can be clearly distinguished through
the prefix coauthors > ERROR:. This helps users reading the logs to
easily differentiate between regular logs and error logs. It also makes
it more suitable for integration with external logging systems (e.g.,
ELK stack, Splunk, etc.). A clear identifier for error logs (coauthors >
ERROR:) makes it easier to automate log analysis and filter specific
types of logs.

- Ease of debugging: Before the change, when an error occurred, the
entire stack trace was printed, requiring going through a lot of
information to find the actual error message. After the change, only the
relevant error message is succinctly printed, allowing for quicker
identification of the problem's cause.


I would appreciate your opinion on this simple feature addition. Have a
good day.


## as-is

- error case
```shell
coauthors > start
coauthors > Resolving .git path from /test
node:fs:453
    return binding.readFileUtf8(path, stringToFlags(options.flag));
                   ^
Error: ENOENT: no such file or directory, open 'C:\test\.git\COMMIT_EDITMSG'
    at Object.readFileSync (node:fs:453:20)
    at C:\Users\alstj\OneDrive\Desktop\coauthors\packages\coauthors\dist\index.js:163:42
    at Generator.next (<anonymous>)
    at C:\Users\alstj\OneDrive\Desktop\coauthors\packages\coauthors\dist\index.js:42:61
    at new Promise (<anonymous>)
    at __async (C:\Users\alstj\OneDrive\Desktop\coauthors\packages\coauthors\dist\index.js:26:10)
    at prepareCommitMsg (C:\Users\alstj\OneDrive\Desktop\coauthors\packages\coauthors\dist\index.js:154:30)
    at Object.<anonymous> (C:\Users\alstj\OneDrive\Desktop\coauthors\packages\coauthors\dist\index.js:184:3)
    at Generator.next (<anonymous>)
    at C:\Users\alstj\OneDrive\Desktop\coauthors\packages\coauthors\dist\index.js:42:61 {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\test\\.git\\COMMIT_EDITMSG'
}
```

## to-be

![image](https://github.com/coauthors/coauthors/assets/60251579/9864772d-c827-46bd-8e90-d8cb0114bcc5)


## PR Checklist

- [x] I did below actions if need

1. I read the [Contributing
Guide](https://github.com/coauthors/coauthors/blob/main/CONTRIBUTING.md)
2. I added documents and tests. ( #51 )

---------

Co-authored-by: Jonghyeon Ko <jonghyeon@toss.im>